# app/config/routing.yml
# Usando Controlador
#pagina_ayuda:
#    path: /ayuda
#    defaults: { _controller: OfertaBundle:Default:ayuda }

# Sin usar controlador
#pagina_ayuda:
#    path: /ayuda
#    defaults: { _controller: FrameworkBundle:Template:template,
#                template: 'OfertaBundle:Default:ayuda.html.twig'}

# Enrutamiento de paginas estaticas
pagina_estatica:
    resource: routing_paginas.yml
    prefix:   /pagina
    defaults: { _controller: FrameworkBundle:Template:template}

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
portada:
    path:     /
    defaults: { _controller: OfertaBundle:Default:portada }
