# app/config/routing_paginas.yml
pagina_ayuda:
    path:     /ayuda
    defaults: { template: 'OfertaBundle:Sitio:ayuda.html.twig'}
_pagina_ayuda:
    path:     /ayuda/
    defaults: { template: 'OfertaBundle:Sitio:ayuda.html.twig'}

pagina_privacidad:
    path:     /privacidad
    defaults: { template: 'OfertaBundle:Sitio:privacidad.html.twig'}
_pagina_privacidad:
    path:     /privacidad/
    defaults: { template: 'OfertaBundle:Sitio:privacidad.html.twig'}

pagina_condiciones:
    path:     /terminos-y-condiciones
    defaults: { template: 'OfertaBundle:Sitio:condiciones.html.twig'}
_pagina_condiciones:
    path:     /terminos-y-condiciones/
    defaults: { template: 'OfertaBundle:Sitio:condiciones.html.twig'}


